# используем язык java.
language: java
jdk: openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database vacancy;' -U postgres
  - psql -c 'create database secret;' -U postgres

# Статистика по JaCoCo
# Используется сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала.
notifications:
  email:
    recipients:
      - david.klarson@mail.ru
    on_success: never # default: changed
    on_failure: always # default: always
