# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database vacancy;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - david.klarson@mail.ru
    on_success: never # default: changed
    on_failure: always # default: always
