# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

before_install:
    - sudo apt-get install sqlite3
    - echo "CREATE TABLE IF NOT EXISTS vacancy
      (
      id           serial primary key,
      date_vacancy character varying(20)   NOT NULL,
      name_vacancy character varying(2000) UNIQUE NOT NULL,
      desc_vacancy text,
      link_vacancy character varying(2000) NOT NULL
      );"
    - echo "CREATE TABLE IF NOT EXISTS item
      (
      id        serial primary key,
      id_item   character varying(2000) NOT NULL,
      name_item character varying(2000) NOT NULL,
      desc_item text
      );
      "
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - david.klarson@mail.ru
    on_success: never # default: changed
    on_failure: always # default: always
